version: "3.8"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kuau
      MYSQL_DATABASE: school-classes-management
    volumes:
      - school-classes-db:/var/lib/mysql
volumes:
  school-classes-db: